### PR TITLE
Wappalyzer Update 2020-03-31

### PR DESCRIPTION
**Pull request by kingthorin**
Updates based on AliasIO/Wappalyzer@a805ebce

### CODE REVIEW

**Comment by kingthorin** [comment]
This PR was automatically raised by a github action, obviously my fork was out-of-date. But this is a step closer 👍 

I'll clean this one up.

**Comment by kingthorin** [comment]
Ready for review

**Comment by thc202** [comment]
Meant for zaproxy/zap-extensions?

**Comment by kingthorin** [comment]
Thanks, yup botched that. Will fix.

**Comment by kingthorin** [comment]
I guess I should have set the target branch as upstream/master (and have set upstream)

**Pull request closed without merging**
